name: Manual deployement

on:
  push:
    branches:
      - 75-deployement-on-gcp

jobs:
  build_api_image:
    name: Build and Push Docker Image for apiTimeManager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: gotime-403610

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          cd back-cryptou
          docker build -f Dockerfile.prod -t eu.gcr.io/cryptou/cryptou-api:latest .
          docker push eu.gcr.io/cryptou/cryptou-api:latest
          
          cd ../front-cryptou
          docker build -f Dockerfile.prod -t eu.gcr.io/cryptou/cryptou-client:latest .
          docker push eu.gcr.io/cryptou/cryptou-client:latest

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          gcloud container clusters get-credentials cryptou --zone europe-west1 --project cryptou
          gcloud components install kubectl

      - name: Deploy new image
        run: |
          kubectl apply -f cryptou-deployement.yaml
