name: Manual deployement

on:
  workflow_dispatch:

jobs:
  build_api_image:
    name: Build and Push Docker Image for apiTimeManager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: gotime-403610

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          cd apiTimemanager
          docker build -t eu.gcr.io/gotime-403610/gotime-api:latest .
          docker push eu.gcr.io/gotime-403610/gotime-api:latest
          
          cd ../clientTimeManager
          docker build -f Dockerfile.prod -t eu.gcr.io/gotime-403610/gotime-client:latest .
          docker push eu.gcr.io/gotime-403610/gotime-client:latest

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          gcloud container clusters get-credentials gotime --zone europe-west9 --project gotime-403610
          gcloud components install kubectl

      - name: Deploy new image
        run: |
          kubectl apply -f gotime-deployement.yaml
